clc; clear all; close all;

g1 = zeros(600, 600);
g1(100:500, 250:350) = 1;
g2 = phantom('Modified Shepp-Logan', 600);
D = 1.5 * hypot(size(g1, 1), size(g1,2))/2;
B1_line = fanbeam(g1, D, 'FanSensorGeometry', ...
    'line', 'FanRotationIncrement', 0.5, 'FanSensorSpacing', 1);
B2_arc = fanbeam(g2, D, 'FanSensorGeometry', ...
    'arc', 'FanRotationIncrement', 0.5, 'FanSensorSpacing', 0.08);
P1_line = fan2para(B1_line, D, 'FanRotationIncrement', 0.5, ...
    'FanSensorGeometry', 'line', ...
    'FanSensorSpacing', 1, ...
    'ParallelCoverage', 'halfcycle', ...
    'ParallelRotationIncrement', 0.5, ...
    'ParallelSensorSpacing', 1);
P2_arc = fan2para(B2_arc,  D, 'FanRotationIncrement', 0.5, ...
    'FanSensorGeometry', 'arc', ...
    'FanSensorSpacing', 0.08, ...
    'ParallelCoverage', 'halfcycle', ...
    'ParallelRotationIncrement', 0.5, ...
    'ParallelSensorSpacing', 1);
P1_line = flipud(P1_line');
P2_arc = flipud(P2_arc');

subplot(2,2,1), imshow(P1_line, []);

subplot(2,2,2), imshow(P2_arc, []);
% subplot(2,2,3), imshow(f2, []);
% subplot(2,2,4), imshow(f3, []);
